### ISSUE TITLE
Optional iron dependency?

### ISSUE THREAD

**Issue by aka-demik** [rustless/rustless#68]
I'm a little confused with line [default = ["iron_backend"]](https://github.com/rustless/rustless/blob/368d0291c1c9d806f03048d74680eee13c7e477a/Cargo.toml#L22) in Cargo.toml. Why is it optional?

Currently it is not working `src/lib.rs:13:1: 13:19 error: can't find crate for `iron` [E0463]`:
```toml
[dependencies.rustless]
version = "0.7.*"
default-features = false
```
It is for the future? Multi-backend?
